### ISSUE TITLE
Save & Load Feature

### ISSUE THREAD

**Issue by ProjectEXT** [boot-game/sokodot#4]
Simple Saving and Loading mechanism for our game

when the player exits a current level, save their location and moves amount.

If the player wins, save their moves amount and the level number they will be transferring to as their current level.

**Comment by gerep** [comment]
The save functionality gets called when the player wins the current level.

The game is loaded when the player clicks "Play".

I don't think we need to store the player's level position or give an option to save during the gameplay.
